# Generated by Django 4.1 on 2024-03-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities_CSV',
            fields=[
                ('big_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=200)),
                ('day_of_week', models.CharField(max_length=200)),
                ('amenity_code', models.CharField(max_length=150)),
                ('iventory', models.CharField(default=100, max_length=200)),
                ('reserved', models.CharField(default=0, max_length=200)),
                ('date_of_input', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('big_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('date_of_arrival', models.CharField(max_length=100)),
                ('date_of_departure', models.CharField(max_length=100)),
                ('num_of_fruit', models.IntegerField(blank=True, default=1, null=True)),
                ('day_of_week', models.CharField(max_length=200)),
                ('item_code', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('special_occasion', models.CharField(blank=True, choices=[('VIP3ME', 'VIP3ME'), ('VIP1', 'VIP1'), ('Presidential', 'Presidential'), ('VIP3', 'VIP3'), ('VIP2', 'VIP2'), ('None', 'None'), ('VIP6', 'VIP6'), ('VIP4', 'VIP4'), ('VIP4ME', 'VIP4ME'), ('VIP5', 'VIP5'), ('VIP5ME', 'VIP5ME')], max_length=300, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('big_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='csv_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_replen', models.CharField(max_length=300)),
                ('amount_day', models.IntegerField(blank=True, default=0)),
                ('date_of_input', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spacial_Amenities',
            fields=[
                ('big_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('day_of_week', models.CharField(blank=True, choices=[('Wednesday', 'Wednesday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Monday', 'Monday')], max_length=200)),
                ('amenity_type', models.CharField(blank=True, choices=[('Birthday cake', 'Birthday cake'), ('Sliced fruit platter', 'Sliced fruit platter'), ('8" cake', '8" cake'), ('Celebration cake', 'Celebration cake'), ('Special amenities', 'Special amenities'), ('Canapes', 'Canapes'), ('6" cake', '6" cake'), ('Aniversary cake', 'Aniversary cake'), ('Honeymoon cake', 'Honeymoon cake')], max_length=250)),
                ('amenity_code', models.CharField(blank=True, choices=[('VIP3ME', 'VIP3ME'), ('VIP1', 'VIP1'), ('Presidential', 'Presidential'), ('VIP3', 'VIP3'), ('VIP2', 'VIP2'), ('None', 'None'), ('VIP6', 'VIP6'), ('VIP4', 'VIP4'), ('VIP4ME', 'VIP4ME'), ('VIP5', 'VIP5'), ('VIP5ME', 'VIP5ME')], max_length=150)),
                ('amenity_amount', models.IntegerField(default=0)),
                ('date_of_input', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
