# Generated by Django 4.1 on 2024-04-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_amenity_special_occasion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amount',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='special_occasion',
            field=models.CharField(blank=True, choices=[('VIP3ME', 'VIP3ME'), ('VIP5ME', 'VIP5ME'), ('VIP4ME', 'VIP4ME'), ('None', 'None'), ('Presidential', 'Presidential'), ('VIP3', 'VIP3'), ('VIP1', 'VIP1'), ('VIP5', 'VIP5'), ('VIP2', 'VIP2'), ('VIP4', 'VIP4'), ('VIP6', 'VIP6')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_code',
            field=models.CharField(blank=True, choices=[('VIP3ME', 'VIP3ME'), ('VIP5ME', 'VIP5ME'), ('VIP4ME', 'VIP4ME'), ('None', 'None'), ('Presidential', 'Presidential'), ('VIP3', 'VIP3'), ('VIP1', 'VIP1'), ('VIP5', 'VIP5'), ('VIP2', 'VIP2'), ('VIP4', 'VIP4'), ('VIP6', 'VIP6')], max_length=150),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_type',
            field=models.CharField(blank=True, choices=[('Birthday cake', 'Birthday cake'), ('Celebration cake', 'Celebration cake'), ('Aniversary cake', 'Aniversary cake'), ('Special amenities', 'Special amenities'), ('Honeymoon cake', 'Honeymoon cake'), ('Canapes', 'Canapes'), ('Sliced fruit platter', 'Sliced fruit platter'), ('6" cake', '6" cake'), ('8" cake', '8" cake')], max_length=250),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday')], max_length=200),
        ),
    ]
