# Generated by Django 4.1 on 2024-04-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_amenity_amount_alter_amenity_special_occasion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities_csv',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='special_occasion',
            field=models.CharField(blank=True, choices=[('VIP2', 'VIP2'), ('VIP6', 'VIP6'), ('None', 'None'), ('Presidential', 'Presidential'), ('VIP1', 'VIP1'), ('VIP4', 'VIP4'), ('VIP4ME', 'VIP4ME'), ('VIP5ME', 'VIP5ME'), ('VIP5', 'VIP5'), ('VIP3', 'VIP3'), ('VIP3ME', 'VIP3ME')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_code',
            field=models.CharField(blank=True, choices=[('VIP2', 'VIP2'), ('VIP6', 'VIP6'), ('None', 'None'), ('Presidential', 'Presidential'), ('VIP1', 'VIP1'), ('VIP4', 'VIP4'), ('VIP4ME', 'VIP4ME'), ('VIP5ME', 'VIP5ME'), ('VIP5', 'VIP5'), ('VIP3', 'VIP3'), ('VIP3ME', 'VIP3ME')], max_length=150),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_type',
            field=models.CharField(blank=True, choices=[('6" cake', '6" cake'), ('Celebration cake', 'Celebration cake'), ('Aniversary cake', 'Aniversary cake'), ('Honeymoon cake', 'Honeymoon cake'), ('Birthday cake', 'Birthday cake'), ('Special amenities', 'Special amenities'), ('Canapes', 'Canapes'), ('Sliced fruit platter', 'Sliced fruit platter'), ('8" cake', '8" cake')], max_length=250),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Wednesday', 'Wednesday')], max_length=200),
        ),
    ]
