# Generated by Django 4.1 on 2024-04-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_amenities_csv_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='num_of_fruit',
        ),
        migrations.AlterField(
            model_name='amenity',
            name='special_occasion',
            field=models.CharField(blank=True, choices=[('VIP4ME', 'VIP4ME'), ('VIP5ME', 'VIP5ME'), ('VIP4', 'VIP4'), ('Presidential', 'Presidential'), ('VIP2', 'VIP2'), ('VIP3ME', 'VIP3ME'), ('VIP5', 'VIP5'), ('VIP3', 'VIP3'), ('VIP1', 'VIP1'), ('VIP6', 'VIP6'), ('None', 'None')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_code',
            field=models.CharField(blank=True, choices=[('VIP4ME', 'VIP4ME'), ('VIP5ME', 'VIP5ME'), ('VIP4', 'VIP4'), ('Presidential', 'Presidential'), ('VIP2', 'VIP2'), ('VIP3ME', 'VIP3ME'), ('VIP5', 'VIP5'), ('VIP3', 'VIP3'), ('VIP1', 'VIP1'), ('VIP6', 'VIP6'), ('None', 'None')], max_length=150),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_type',
            field=models.CharField(blank=True, choices=[('8" cake', '8" cake'), ('Celebration cake', 'Celebration cake'), ('Aniversary cake', 'Aniversary cake'), ('Sliced fruit platter', 'Sliced fruit platter'), ('Special amenities', 'Special amenities'), ('Honeymoon cake', 'Honeymoon cake'), ('6" cake', '6" cake'), ('Canapes', 'Canapes'), ('Birthday cake', 'Birthday cake')], max_length=250),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=200),
        ),
    ]
