# Generated by Django 4.1 on 2024-04-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_amenity_num_of_fruit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='special_occasion',
            field=models.CharField(blank=True, choices=[('VIP1', 'VIP1'), ('Presidential', 'Presidential'), ('None', 'None'), ('VIP6', 'VIP6'), ('VIP2', 'VIP2'), ('VIP4ME', 'VIP4ME'), ('VIP3', 'VIP3'), ('VIP5ME', 'VIP5ME'), ('VIP4', 'VIP4'), ('VIP5', 'VIP5'), ('VIP3ME', 'VIP3ME')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_code',
            field=models.CharField(blank=True, choices=[('VIP1', 'VIP1'), ('Presidential', 'Presidential'), ('None', 'None'), ('VIP6', 'VIP6'), ('VIP2', 'VIP2'), ('VIP4ME', 'VIP4ME'), ('VIP3', 'VIP3'), ('VIP5ME', 'VIP5ME'), ('VIP4', 'VIP4'), ('VIP5', 'VIP5'), ('VIP3ME', 'VIP3ME')], max_length=150),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='amenity_type',
            field=models.CharField(blank=True, choices=[('6" cake', '6" cake'), ('8" cake', '8" cake'), ('Special amenities', 'Special amenities'), ('Aniversary cake', 'Aniversary cake'), ('Celebration cake', 'Celebration cake'), ('Honeymoon cake', 'Honeymoon cake'), ('Sliced fruit platter', 'Sliced fruit platter'), ('Canapes', 'Canapes'), ('Birthday cake', 'Birthday cake')], max_length=250),
        ),
        migrations.AlterField(
            model_name='spacial_amenities',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday')], max_length=200),
        ),
    ]
